---
name: release

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    uses: hugoh/gh-workflows/.github/workflows/release.yml@a9aaf5e41e2e7e2312899bfe4e1a819f9e4b5c4e # v1.22.0
    permissions:
      contents: write
    with:
      major-tag: true
